// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hapi/release/hook.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hapi.Release {

  /// <summary>Holder for reflection information generated from hapi/release/hook.proto</summary>
  public static partial class HookReflection {

    #region Descriptor
    /// <summary>File descriptor for hapi/release/hook.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HookReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdoYXBpL3JlbGVhc2UvaG9vay5wcm90bxIMaGFwaS5yZWxlYXNlGh9nb29n",
            "bGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIuYDCgRIb29rEgwKBG5hbWUY",
            "ASABKAkSDAoEa2luZBgCIAEoCRIMCgRwYXRoGAMgASgJEhAKCG1hbmlmZXN0",
            "GAQgASgJEigKBmV2ZW50cxgFIAMoDjIYLmhhcGkucmVsZWFzZS5Ib29rLkV2",
            "ZW50EiwKCGxhc3RfcnVuGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVz",
            "dGFtcBIOCgZ3ZWlnaHQYByABKAUSOAoPZGVsZXRlX3BvbGljaWVzGAggAygO",
            "Mh8uaGFwaS5yZWxlYXNlLkhvb2suRGVsZXRlUG9saWN5ItQBCgVFdmVudBIL",
            "CgdVTktOT1dOEAASDwoLUFJFX0lOU1RBTEwQARIQCgxQT1NUX0lOU1RBTEwQ",
            "AhIOCgpQUkVfREVMRVRFEAMSDwoLUE9TVF9ERUxFVEUQBBIPCgtQUkVfVVBH",
            "UkFERRAFEhAKDFBPU1RfVVBHUkFERRAGEhAKDFBSRV9ST0xMQkFDSxAHEhEK",
            "DVBPU1RfUk9MTEJBQ0sQCBIYChRSRUxFQVNFX1RFU1RfU1VDQ0VTUxAJEhgK",
            "FFJFTEVBU0VfVEVTVF9GQUlMVVJFEAoiKQoMRGVsZXRlUG9saWN5Eg0KCVNV",
            "Q0NFRURFRBAAEgoKBkZBSUxFRBABQglaB3JlbGVhc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hapi.Release.Hook), global::Hapi.Release.Hook.Parser, new[]{ "Name", "Kind", "Path", "Manifest", "Events", "LastRun", "Weight", "DeletePolicies" }, null, new[]{ typeof(global::Hapi.Release.Hook.Types.Event), typeof(global::Hapi.Release.Hook.Types.DeletePolicy) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Hook defines a hook object.
  /// </summary>
  public sealed partial class Hook : pb::IMessage<Hook> {
    private static readonly pb::MessageParser<Hook> _parser = new pb::MessageParser<Hook>(() => new Hook());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Hook> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hapi.Release.HookReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hook() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hook(Hook other) : this() {
      name_ = other.name_;
      kind_ = other.kind_;
      path_ = other.path_;
      manifest_ = other.manifest_;
      events_ = other.events_.Clone();
      LastRun = other.lastRun_ != null ? other.LastRun.Clone() : null;
      weight_ = other.weight_;
      deletePolicies_ = other.deletePolicies_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Hook Clone() {
      return new Hook(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 2;
    private string kind_ = "";
    /// <summary>
    /// Kind is the Kubernetes kind.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Kind {
      get { return kind_; }
      set {
        kind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 3;
    private string path_ = "";
    /// <summary>
    /// Path is the chart-relative path to the template.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "manifest" field.</summary>
    public const int ManifestFieldNumber = 4;
    private string manifest_ = "";
    /// <summary>
    /// Manifest is the manifest contents.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Manifest {
      get { return manifest_; }
      set {
        manifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Hapi.Release.Hook.Types.Event> _repeated_events_codec
        = pb::FieldCodec.ForEnum(42, x => (int) x, x => (global::Hapi.Release.Hook.Types.Event) x);
    private readonly pbc::RepeatedField<global::Hapi.Release.Hook.Types.Event> events_ = new pbc::RepeatedField<global::Hapi.Release.Hook.Types.Event>();
    /// <summary>
    /// Events are the events that this hook fires on.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Hapi.Release.Hook.Types.Event> Events {
      get { return events_; }
    }

    /// <summary>Field number for the "last_run" field.</summary>
    public const int LastRunFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastRun_;
    /// <summary>
    /// LastRun indicates the date/time this was last run.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastRun {
      get { return lastRun_; }
      set {
        lastRun_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 7;
    private int weight_;
    /// <summary>
    /// Weight indicates the sort order for execution among similar Hook type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "delete_policies" field.</summary>
    public const int DeletePoliciesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Hapi.Release.Hook.Types.DeletePolicy> _repeated_deletePolicies_codec
        = pb::FieldCodec.ForEnum(66, x => (int) x, x => (global::Hapi.Release.Hook.Types.DeletePolicy) x);
    private readonly pbc::RepeatedField<global::Hapi.Release.Hook.Types.DeletePolicy> deletePolicies_ = new pbc::RepeatedField<global::Hapi.Release.Hook.Types.DeletePolicy>();
    /// <summary>
    /// DeletePolicies are the policies that indicate when to delete the hook
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Hapi.Release.Hook.Types.DeletePolicy> DeletePolicies {
      get { return deletePolicies_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Hook);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Hook other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Kind != other.Kind) return false;
      if (Path != other.Path) return false;
      if (Manifest != other.Manifest) return false;
      if(!events_.Equals(other.events_)) return false;
      if (!object.Equals(LastRun, other.LastRun)) return false;
      if (Weight != other.Weight) return false;
      if(!deletePolicies_.Equals(other.deletePolicies_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Kind.Length != 0) hash ^= Kind.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (Manifest.Length != 0) hash ^= Manifest.GetHashCode();
      hash ^= events_.GetHashCode();
      if (lastRun_ != null) hash ^= LastRun.GetHashCode();
      if (Weight != 0) hash ^= Weight.GetHashCode();
      hash ^= deletePolicies_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Kind.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Kind);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (Manifest.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Manifest);
      }
      events_.WriteTo(output, _repeated_events_codec);
      if (lastRun_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LastRun);
      }
      if (Weight != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Weight);
      }
      deletePolicies_.WriteTo(output, _repeated_deletePolicies_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Kind.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Kind);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (Manifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Manifest);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      if (lastRun_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastRun);
      }
      if (Weight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Weight);
      }
      size += deletePolicies_.CalculateSize(_repeated_deletePolicies_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Hook other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Kind.Length != 0) {
        Kind = other.Kind;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.Manifest.Length != 0) {
        Manifest = other.Manifest;
      }
      events_.Add(other.events_);
      if (other.lastRun_ != null) {
        if (lastRun_ == null) {
          lastRun_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastRun.MergeFrom(other.LastRun);
      }
      if (other.Weight != 0) {
        Weight = other.Weight;
      }
      deletePolicies_.Add(other.deletePolicies_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Kind = input.ReadString();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            Manifest = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
          case 50: {
            if (lastRun_ == null) {
              lastRun_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(lastRun_);
            break;
          }
          case 56: {
            Weight = input.ReadInt32();
            break;
          }
          case 66:
          case 64: {
            deletePolicies_.AddEntriesFrom(input, _repeated_deletePolicies_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Hook message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Event {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("PRE_INSTALL")] PreInstall = 1,
        [pbr::OriginalName("POST_INSTALL")] PostInstall = 2,
        [pbr::OriginalName("PRE_DELETE")] PreDelete = 3,
        [pbr::OriginalName("POST_DELETE")] PostDelete = 4,
        [pbr::OriginalName("PRE_UPGRADE")] PreUpgrade = 5,
        [pbr::OriginalName("POST_UPGRADE")] PostUpgrade = 6,
        [pbr::OriginalName("PRE_ROLLBACK")] PreRollback = 7,
        [pbr::OriginalName("POST_ROLLBACK")] PostRollback = 8,
        [pbr::OriginalName("RELEASE_TEST_SUCCESS")] ReleaseTestSuccess = 9,
        [pbr::OriginalName("RELEASE_TEST_FAILURE")] ReleaseTestFailure = 10,
      }

      public enum DeletePolicy {
        [pbr::OriginalName("SUCCEEDED")] Succeeded = 0,
        [pbr::OriginalName("FAILED")] Failed = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
