// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/release/status.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hapi.Release {

  /// <summary>Holder for reflection information generated from hapi/release/status.proto</summary>
  public static partial class StatusReflection {

    #region Descriptor
    /// <summary>File descriptor for hapi/release/status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChloYXBpL3JlbGVhc2Uvc3RhdHVzLnByb3RvEgxoYXBpLnJlbGVhc2UaHWhh",
            "cGkvcmVsZWFzZS90ZXN0X3N1aXRlLnByb3RvGhlnb29nbGUvcHJvdG9idWYv",
            "YW55LnByb3RvIqQCCgZTdGF0dXMSJwoEY29kZRgBIAEoDjIZLmhhcGkucmVs",
            "ZWFzZS5TdGF0dXMuQ29kZRIRCglyZXNvdXJjZXMYAyABKAkSDQoFbm90ZXMY",
            "BCABKAkSNAoTbGFzdF90ZXN0X3N1aXRlX3J1bhgFIAEoCzIXLmhhcGkucmVs",
            "ZWFzZS5UZXN0U3VpdGUimAEKBENvZGUSCwoHVU5LTk9XThAAEgwKCERFUExP",
            "WUVEEAESCwoHREVMRVRFRBACEg4KClNVUEVSU0VERUQQAxIKCgZGQUlMRUQQ",
            "BBIMCghERUxFVElORxAFEhMKD1BFTkRJTkdfSU5TVEFMTBAGEhMKD1BFTkRJ",
            "TkdfVVBHUkFERRAHEhQKEFBFTkRJTkdfUk9MTEJBQ0sQCEIJWgdyZWxlYXNl",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Hapi.Release.TestSuiteReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hapi.Release.Status), global::Hapi.Release.Status.Parser, new[]{ "Code", "Resources", "Notes", "LastTestSuiteRun" }, null, new[]{ typeof(global::Hapi.Release.Status.Types.Code) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Status defines the status of a release.
  /// </summary>
  public sealed partial class Status : pb::IMessage<Status> {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hapi.Release.StatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status(Status other) : this() {
      code_ = other.code_;
      resources_ = other.resources_;
      notes_ = other.notes_;
      LastTestSuiteRun = other.lastTestSuiteRun_ != null ? other.LastTestSuiteRun.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Hapi.Release.Status.Types.Code code_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Hapi.Release.Status.Types.Code Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 3;
    private string resources_ = "";
    /// <summary>
    /// Cluster resources as kubectl would print them.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Resources {
      get { return resources_; }
      set {
        resources_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "notes" field.</summary>
    public const int NotesFieldNumber = 4;
    private string notes_ = "";
    /// <summary>
    /// Contains the rendered templates/NOTES.txt if available
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Notes {
      get { return notes_; }
      set {
        notes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_test_suite_run" field.</summary>
    public const int LastTestSuiteRunFieldNumber = 5;
    private global::Hapi.Release.TestSuite lastTestSuiteRun_;
    /// <summary>
    /// LastTestSuiteRun provides results on the last test run on a release
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Hapi.Release.TestSuite LastTestSuiteRun {
      get { return lastTestSuiteRun_; }
      set {
        lastTestSuiteRun_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Resources != other.Resources) return false;
      if (Notes != other.Notes) return false;
      if (!object.Equals(LastTestSuiteRun, other.LastTestSuiteRun)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Resources.Length != 0) hash ^= Resources.GetHashCode();
      if (Notes.Length != 0) hash ^= Notes.GetHashCode();
      if (lastTestSuiteRun_ != null) hash ^= LastTestSuiteRun.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Resources.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Resources);
      }
      if (Notes.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Notes);
      }
      if (lastTestSuiteRun_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LastTestSuiteRun);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Resources.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resources);
      }
      if (Notes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notes);
      }
      if (lastTestSuiteRun_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastTestSuiteRun);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Resources.Length != 0) {
        Resources = other.Resources;
      }
      if (other.Notes.Length != 0) {
        Notes = other.Notes;
      }
      if (other.lastTestSuiteRun_ != null) {
        if (lastTestSuiteRun_ == null) {
          lastTestSuiteRun_ = new global::Hapi.Release.TestSuite();
        }
        LastTestSuiteRun.MergeFrom(other.LastTestSuiteRun);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            code_ = (global::Hapi.Release.Status.Types.Code) input.ReadEnum();
            break;
          }
          case 26: {
            Resources = input.ReadString();
            break;
          }
          case 34: {
            Notes = input.ReadString();
            break;
          }
          case 42: {
            if (lastTestSuiteRun_ == null) {
              lastTestSuiteRun_ = new global::Hapi.Release.TestSuite();
            }
            input.ReadMessage(lastTestSuiteRun_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Status message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Code {
        /// <summary>
        /// Status_UNKNOWN indicates that a release is in an uncertain state.
        /// </summary>
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        /// <summary>
        /// Status_DEPLOYED indicates that the release has been pushed to Kubernetes.
        /// </summary>
        [pbr::OriginalName("DEPLOYED")] Deployed = 1,
        /// <summary>
        /// Status_DELETED indicates that a release has been deleted from Kubermetes.
        /// </summary>
        [pbr::OriginalName("DELETED")] Deleted = 2,
        /// <summary>
        /// Status_SUPERSEDED indicates that this release object is outdated and a newer one exists.
        /// </summary>
        [pbr::OriginalName("SUPERSEDED")] Superseded = 3,
        /// <summary>
        /// Status_FAILED indicates that the release was not successfully deployed.
        /// </summary>
        [pbr::OriginalName("FAILED")] Failed = 4,
        /// <summary>
        /// Status_DELETING indicates that a delete operation is underway.
        /// </summary>
        [pbr::OriginalName("DELETING")] Deleting = 5,
        /// <summary>
        /// Status_PENDING_INSTALL indicates that an install operation is underway.
        /// </summary>
        [pbr::OriginalName("PENDING_INSTALL")] PendingInstall = 6,
        /// <summary>
        /// Status_PENDING_UPGRADE indicates that an upgrade operation is underway.
        /// </summary>
        [pbr::OriginalName("PENDING_UPGRADE")] PendingUpgrade = 7,
        /// <summary>
        /// Status_PENDING_ROLLBACK indicates that an rollback operation is underway.
        /// </summary>
        [pbr::OriginalName("PENDING_ROLLBACK")] PendingRollback = 8,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
