// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hapi/release/test_run.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hapi.Release {

  /// <summary>Holder for reflection information generated from hapi/release/test_run.proto</summary>
  public static partial class TestRunReflection {

    #region Descriptor
    /// <summary>File descriptor for hapi/release/test_run.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestRunReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtoYXBpL3JlbGVhc2UvdGVzdF9ydW4ucHJvdG8SDGhhcGkucmVsZWFzZRof",
            "Z29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byLzAQoHVGVzdFJ1bhIM",
            "CgRuYW1lGAEgASgJEiwKBnN0YXR1cxgCIAEoDjIcLmhhcGkucmVsZWFzZS5U",
            "ZXN0UnVuLlN0YXR1cxIMCgRpbmZvGAMgASgJEi4KCnN0YXJ0ZWRfYXQYBCAB",
            "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDGNvbXBsZXRlZF9h",
            "dBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiPAoGU3RhdHVz",
            "EgsKB1VOS05PV04QABILCgdTVUNDRVNTEAESCwoHRkFJTFVSRRACEgsKB1JV",
            "Tk5JTkcQA0IJWgdyZWxlYXNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hapi.Release.TestRun), global::Hapi.Release.TestRun.Parser, new[]{ "Name", "Status", "Info", "StartedAt", "CompletedAt" }, null, new[]{ typeof(global::Hapi.Release.TestRun.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TestRun : pb::IMessage<TestRun> {
    private static readonly pb::MessageParser<TestRun> _parser = new pb::MessageParser<TestRun>(() => new TestRun());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestRun> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hapi.Release.TestRunReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRun() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRun(TestRun other) : this() {
      name_ = other.name_;
      status_ = other.status_;
      info_ = other.info_;
      StartedAt = other.startedAt_ != null ? other.StartedAt.Clone() : null;
      CompletedAt = other.completedAt_ != null ? other.CompletedAt.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestRun Clone() {
      return new TestRun(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::Hapi.Release.TestRun.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Hapi.Release.TestRun.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 3;
    private string info_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Info {
      get { return info_; }
      set {
        info_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "started_at" field.</summary>
    public const int StartedAtFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp startedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp StartedAt {
      get { return startedAt_; }
      set {
        startedAt_ = value;
      }
    }

    /// <summary>Field number for the "completed_at" field.</summary>
    public const int CompletedAtFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp completedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CompletedAt {
      get { return completedAt_; }
      set {
        completedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestRun);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestRun other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Status != other.Status) return false;
      if (Info != other.Info) return false;
      if (!object.Equals(StartedAt, other.StartedAt)) return false;
      if (!object.Equals(CompletedAt, other.CompletedAt)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (Info.Length != 0) hash ^= Info.GetHashCode();
      if (startedAt_ != null) hash ^= StartedAt.GetHashCode();
      if (completedAt_ != null) hash ^= CompletedAt.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Status != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Info.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Info);
      }
      if (startedAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StartedAt);
      }
      if (completedAt_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CompletedAt);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Info.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Info);
      }
      if (startedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartedAt);
      }
      if (completedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CompletedAt);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestRun other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.Info.Length != 0) {
        Info = other.Info;
      }
      if (other.startedAt_ != null) {
        if (startedAt_ == null) {
          startedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        StartedAt.MergeFrom(other.StartedAt);
      }
      if (other.completedAt_ != null) {
        if (completedAt_ == null) {
          completedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CompletedAt.MergeFrom(other.CompletedAt);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            status_ = (global::Hapi.Release.TestRun.Types.Status) input.ReadEnum();
            break;
          }
          case 26: {
            Info = input.ReadString();
            break;
          }
          case 34: {
            if (startedAt_ == null) {
              startedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(startedAt_);
            break;
          }
          case 42: {
            if (completedAt_ == null) {
              completedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(completedAt_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TestRun message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("FAILURE")] Failure = 2,
        [pbr::OriginalName("RUNNING")] Running = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
