// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hapi/release/test_suite.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hapi.Release {

  /// <summary>Holder for reflection information generated from hapi/release/test_suite.proto</summary>
  public static partial class TestSuiteReflection {

    #region Descriptor
    /// <summary>File descriptor for hapi/release/test_suite.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestSuiteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1oYXBpL3JlbGVhc2UvdGVzdF9zdWl0ZS5wcm90bxIMaGFwaS5yZWxlYXNl",
            "Gh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGhtoYXBpL3JlbGVh",
            "c2UvdGVzdF9ydW4ucHJvdG8ilQEKCVRlc3RTdWl0ZRIuCgpzdGFydGVkX2F0",
            "GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxjb21wbGV0",
            "ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiYKB3Jl",
            "c3VsdHMYAyADKAsyFS5oYXBpLnJlbGVhc2UuVGVzdFJ1bkIJWgdyZWxlYXNl",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Hapi.Release.TestRunReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hapi.Release.TestSuite), global::Hapi.Release.TestSuite.Parser, new[]{ "StartedAt", "CompletedAt", "Results" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// TestSuite comprises of the last run of the pre-defined test suite of a release version
  /// </summary>
  public sealed partial class TestSuite : pb::IMessage<TestSuite> {
    private static readonly pb::MessageParser<TestSuite> _parser = new pb::MessageParser<TestSuite>(() => new TestSuite());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestSuite> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hapi.Release.TestSuiteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestSuite() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestSuite(TestSuite other) : this() {
      StartedAt = other.startedAt_ != null ? other.StartedAt.Clone() : null;
      CompletedAt = other.completedAt_ != null ? other.CompletedAt.Clone() : null;
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestSuite Clone() {
      return new TestSuite(this);
    }

    /// <summary>Field number for the "started_at" field.</summary>
    public const int StartedAtFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp startedAt_;
    /// <summary>
    /// StartedAt indicates the date/time this test suite was kicked off
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp StartedAt {
      get { return startedAt_; }
      set {
        startedAt_ = value;
      }
    }

    /// <summary>Field number for the "completed_at" field.</summary>
    public const int CompletedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp completedAt_;
    /// <summary>
    /// CompletedAt indicates the date/time this test suite was completed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CompletedAt {
      get { return completedAt_; }
      set {
        completedAt_ = value;
      }
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Hapi.Release.TestRun> _repeated_results_codec
        = pb::FieldCodec.ForMessage(26, global::Hapi.Release.TestRun.Parser);
    private readonly pbc::RepeatedField<global::Hapi.Release.TestRun> results_ = new pbc::RepeatedField<global::Hapi.Release.TestRun>();
    /// <summary>
    /// Results are the results of each segment of the test
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Hapi.Release.TestRun> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestSuite);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestSuite other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartedAt, other.StartedAt)) return false;
      if (!object.Equals(CompletedAt, other.CompletedAt)) return false;
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startedAt_ != null) hash ^= StartedAt.GetHashCode();
      if (completedAt_ != null) hash ^= CompletedAt.GetHashCode();
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startedAt_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(StartedAt);
      }
      if (completedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CompletedAt);
      }
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartedAt);
      }
      if (completedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CompletedAt);
      }
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestSuite other) {
      if (other == null) {
        return;
      }
      if (other.startedAt_ != null) {
        if (startedAt_ == null) {
          startedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        StartedAt.MergeFrom(other.StartedAt);
      }
      if (other.completedAt_ != null) {
        if (completedAt_ == null) {
          completedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CompletedAt.MergeFrom(other.CompletedAt);
      }
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (startedAt_ == null) {
              startedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(startedAt_);
            break;
          }
          case 18: {
            if (completedAt_ == null) {
              completedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(completedAt_);
            break;
          }
          case 26: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
